#include <stdio.h>
#include <stdlib.h>

struct Joueur {
    char nom[20];
    int x, y;
    int barrieres_restantes;

};


char plateau[17][17];
struct Joueur joueurs[4];
int nombre_joueurs=0;
int joueur_actuel = 0;


void initialiser_plateau() {
    for (int i = 0; i < 17; i++) {
        for (int j = 0; j < 17; j++) {
            if (i % 2 == 0 && j % 2 == 0) {
                plateau[i][j] = '.';
            } else {
                plateau[i][j] = '+';
            }
        }
    }


    plateau[0][8] = '1';
    plateau[16][8] = '2';
    joueurs[0].x = 0; joueurs[0].y = 8;
    joueurs[1].x = 16; joueurs[1].y = 8;

    if (nombre_joueurs == 4) {
        plateau[8][0] = '3';
        plateau[8][16] = '4';
        joueurs[2].x = 8; joueurs[2].y = 0;
        joueurs[3].x = 8; joueurs[3].y = 16;
    }
}
void afficher_plateau() {
    printf("\n     "); 
    for (int j = 0; j < 17; j++) {
        printf("%2d ", j); 
    }
    printf("\n");

    for (int i = 0; i < 17; i++) {
        printf("%2d   ", i); 
        for (int j = 0; j < 17; j++) {
            printf(" %c ", plateau[i][j]);
        }
        printf("\n");
    }
}


void initialiser_joueurs() {
    while(nombre_joueurs != 4 && nombre_joueurs != 2){
        printf("Entrez le nombre de joueurs (2 ou 4):\n");
        scanf("%d", &nombre_joueurs);
    }

    for (int i = 0; i < nombre_joueurs; i++) {
        printf("Entrez le nom du Joueur %d:\n", i + 1);
        scanf("%s", joueurs[i].nom);
        joueurs[i].barrieres_restantes = 20/nombre_joueurs;
    }
}

void deplacer_pion(struct Joueur *joueur, int numero_joueur) {
int x, y;
int deplacement_valide = 0;

while (!deplacement_valide) {
printf("donner les coordonées %s (ligne col): ", joueur->nom);
scanf("%d %d", &x, &y);


if (x >= 0 && x < 17 && y >= 0 && y < 17 && plateau[x][y] == '.' &&
abs(joueur->x - x) + abs(joueur->y - y) == 2) {
plateau[joueur->x][joueur->y] = '.';  
joueur->x = x;
joueur->y = y;
plateau[x][y] = '1' + numero_joueur; 
deplacement_valide = 1; 
} else {
printf("Déplacement impossible! Essayez à nouveau.\n");
}
}
}


void poser_barriere(struct Joueur *joueur) {
if (joueur->barrieres_restantes > 0) {
int x, y, orientation;
int barriere_valide = 0;

while (!barriere_valide) {
printf("Entrez les coordonnées de la barrière (ligne col, doit être '+'): ");
scanf("%d %d", &x, &y);
printf("Entrez l'orientation (1 pour horizontal, 2 pour vertical): ");
scanf("%d", &orientation);


if (orientation == 1 && x % 2 == 1 && y % 2 == 0 && y + 2 < 17 &&
plateau[x][y] == '+' && plateau[x][y + 2] == '+') {
plateau[x][y] = plateau[x][y + 1] = plateau[x][y + 2] = '-';  
joueur->barrieres_restantes--;
barriere_valide = 1; 
} else if (orientation == 2 && x % 2 == 0 && y % 2 == 1 && x + 2 < 17 &&
plateau[x][y] == '+' && plateau[x + 2][y] == '+') {
plateau[x][y] = plateau[x + 1][y] = plateau[x + 2][y] = '|'; 
joueur->barrieres_restantes--;
barriere_valide = 1; 
} else {
printf("Position  invalide! Essayez à nouveau.\n");
}
}
} else {
printf("Vous n'avez plus de barrières \n");
}
}
